//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySqlModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public product()
        {
            this.sales = new HashSet<sale>();
        }
    
        public int productId { get; set; }
        public string productName { get; set; }
        public int vendorId { get; set; }
        public int measureId { get; set; }
        public int productTypeId { get; set; }
        public decimal productPrice { get; set; }
    
        public virtual measure measure { get; set; }
        public virtual vendor vendor { get; set; }
        public virtual ICollection<sale> sales { get; set; }
    }
}
