//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oracle
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT
    {
        public decimal PRODUCT_ID { get; set; }
        public decimal VENDOR_ID { get; set; }
        public string PRODUCTNAME { get; set; }
        public decimal MEASURE_ID { get; set; }
        public decimal TYPE_ID { get; set; }
        public decimal PRICE { get; set; }
        public bool ISCOPIED { get; set; }
        public bool ISDELETED { get; set; }
    
        public virtual MEASURE MEASURE { get; set; }
        public virtual PRODUCTSTYPE PRODUCTSTYPE { get; set; }
        public virtual VENDOR VENDOR { get; set; }
    }
}
