//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLiteDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaxInformation
    {
        public long Id { get; set; }
        public string ProductName { get; set; }
        public long Tax { get; set; }
    }
}
