//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySqlModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vendor_expenses
    {
        public int vendorId { get; set; }
        public System.DateTime expenseDate { get; set; }
        public decimal total { get; set; }
    
        public virtual vendor vendor { get; set; }
    }
}
